### ISSUE TITLE
Timeout issues in Node 8

### ISSUE THREAD

**Issue by WorldMaker** [jspm/github#117]
I can't get JSPM installs to work in Node 8 due to cycling through GitHub and jspm-git timeouts. Before I revert my install of Node to LTS, I figured I should try to document the problem in case it helps.

One message early in the install:

    warn TypeError: "timeout" must be an unsigned integer
         at validateTimeout (child_process.js:620:11)
         at Object.exports.execFile (child_process.js:183:3)
         at exports.exec (child_process.js:138:18)
         at ~...\node_modules\jspm-github\exec-git.js:54:9
         at initializePromise (~...\node_modules\rsvp\dist\rsvp.js:589:5)
         at new Promise$1 (~...\node_modules\rsvp\dist\rsvp.js:1077:33)
         at ~...\node_modules\jspm-github\exec-git.js:53:14
         at tryCatch (~...\node_modules\rsvp\dist\rsvp.js:539:12)
         at invokeCallback (~...\node_modules\rsvp\dist\rsvp.js:554:13)
         at ~...\node_modules\rsvp\dist\rsvp.js:629:16
         at flush (~...\node_modules\rsvp\dist\rsvp.js:2414:5)
         at _combinedTickCallback (internal/process/next_tick.js:95:7)
         at process._tickCallback (internal/process/next_tick.js:161:9)

Eventually at the end of the install it's just a ton of warnings like this until one of them errors:

    warn Timed out on lookup for github:jspm/nodelibs-tls, retrying (3).
     To increase the timeout run jspm config registries.github.timeouts.lookup 120

I tried increasing the timeout as suggested and that did not appear to help.

Using jspm 0.16.53, Node 8 on Windows.

**Comment by gondalez** [comment]
`npm install jspm-github@0.13.18` solved this for me

**Comment by nonplus** [comment]
`npm install jspm-registry@0.4.4` was also necessary for me

Looks like Node 8 is stricter about the `option.timeout` parameter passed to [child_process](https://nodejs.org/api/child_process.html) methods and no longer coerces a `null` value to `0`.
