### ISSUE TITLE
Error on getPackageConfig with jsmp v0.13.26

### ISSUE THREAD

**Issue by omkarvijf41** [jspm/github#137]
Unauthorized response for GitHub API.

     Use jspm registry config github to reconfigure the credentials, or update them in your ~/.netrc file.
     
     I am getting above error while doing builds. Could you please help us resolving this issue. 
     Thank you in advance.

**Comment by omkarvijf41** [comment]
@guybedford/ Someone could you please help resolving this issue. Multiple apps builds are failings and it's blocking our scheduled releases. Hope you understand the urgency resolving this issue.

**Comment by sudhakar-reddyk** [comment]
I got the same issue, thought to change my git token, But it's also failing iike below
Enter your GitHub password or access token:
err (jspm) Error: Bad GitHub API response code 404: Not Found
    at getAPIToken (/Users/rshn/.nvm/versions/node/v16.1.0/lib/node_modules/jspm/node_modules/@jspm/github/github.js:172:17)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async GithubEndpoint.configure (/Users/rshn/.nvm/versions/node/v16.1.0/lib/node_modules/jspm/node_modules/@jspm/github/github.js:73:5)
    at async RegistryManager.configure (/Users/rshn/.nvm/versions/node/v16.1.0/lib/node_modules/jspm/lib/install/registry-manager.js:134:9)
    at async cliHandler (/Users/rshn/.nvm/versions/node/v16.1.0/lib/node_modules/jspm/lib/cli.js:628:17)

**Comment by rasialaAF** [comment]
Having exactly the same issue since last week while using jspm 0.16.x is there a known solution / workaround ?

**Comment by guybedford** [comment]
Please do confirm you're running the latest jspm-github 0.13.26.

//cc @yafanasiev who worked on the support of the new token format here in https://github.com/jspm/github/pull/135. I'm not sure if this is a problem caused by that PR, or simply a result of the token format change with GitHub.

**Comment by sudhakar-reddyk** [comment]
I'm using 
"jspm": "^0.16.53",
    "jspm-github": "0.13.26",

**Comment by rasialaAF** [comment]
Using:
- jspm 0.16.0
- jspm-github: 0.13.26

Tried old and new token format without any luck

**Comment by yafanasiev** [comment]
Works for me on 

```
    "node_modules/jspm": {      
      "version": "0.16.55" 
      ...  
    "node_modules/jspm-github": {      
      "version": "0.13.26" 
      ...  
```

with new token format. Can you share more details or a minimal reproducible setup? Also, can you check if your install will error on public-only repositories? Token will still be used in requests, but that would eliminate issues with specific private dependencies.

**Comment by rasialaAF** [comment]
Hello @yafanasiev,
We previously only accessed public repositories, I switched them to npm or removed them in order to go forward on debugging.
Still have the errors for required dependencies of jspm (among others):

> warn Error on download for github:jspm/nodelibs-process
     Unauthorized response for GitHub API.
     Use jspm registry config github to reconfigure the credentials, or update them in your ~/.netrc file.

> warn Error on download for github:systemjs/plugin-css
     Unauthorized response for GitHub API.
     Use jspm registry config github to reconfigure the credentials, or update them in your ~/.netrc file.

I tried running the build using jspm 0.16.55 using node 6.15.1, and tried the `jspm registry config github` which outputed that the connection to github is OK.

Don't know if this is important but the `jspm install` is called in the postinstall npm lifecycle like below:
`
"postinstall": "... registry config ... && jspm config registries.github.auth base64encoding(username:githubtoken) && jspm install"
`

**Comment by yafanasiev** [comment]
@sudhakar-reddyk @rasialaAF unfortunately I can't reproduce the issue even on simple setup. I've got a correct request built in https://github.com/jspm/github/blob/872c1671636ecd082b9e04568b789a76f2797c51/github.js#L456, and it returns 200 as expected, so I doubt that there is an issue in Github API. I would recommend manually downgrading `jspm-github` to see if any of recent changes brought this issue, or creating a minimal reproducible repo to check this further.

**Comment by sudhakar-reddyk** [comment]
@yafanasiev what is your setup? what's your git token format how are you providing it to jspm?

**Comment by yafanasiev** [comment]
We use new format token with `repo` permissions, and we set configuration before each build as such:

```
jspm config registries.github.auth <token>
```

**Comment by rasialaAF** [comment]
@yafanasiev @sudhakar-reddyk 

In my case we changed this line:  jspm config registries.github.auth **token**

Where **token** is now the plain new Github token ex: ghp_XXXXX

And now it looks like it works !

Before the modification the token was as per documentation (here: https://jspm.org/docs/0.16/registries.html) 

>  Base64 encoding of the GitHub username and password or access token separated by a :, e.g. username:token

Which doesn't seem to work anymore...

**Comment by jfstephe** [comment]
I went around this several times and I think it probably is ok.

In case this helps I think I had an old format (and expired) token in an env variable, and despite all the jspm config commands I suspect it was still being used. I updated the env var and my problems seem(!) to have gone away.
