### ISSUE TITLE
Invalid tar error when trying to install gauge.js

### ISSUE THREAD

**Issue by Gu1** [jspm/github#61]
I can't seem to be able to install gauge.js from github, i get an error about an invalid tar file.
I tried adding debugging statements to see what file was downloaded, and I can download the tar and extract it just fine.

```
$ jspm install github:bernii/gauge.js
     Looking up github:bernii/gauge.js
     Creating registry cache...
     Downloading github:bernii/gauge.js@1.2.1

warn Error on download for github:bernii/gauge.js, retrying (1).
     Error: invalid tar file
         at Extract.Parse._startEntry (/home/gu1/xx/node_modules/jspm/node_modules/jspm-github/node_modules/tar/lib/parse.js:145:13)
         at Extract.Parse._process (/home/gu1/xx/node_modules/jspm/node_modules/jspm-github/node_modules/tar/lib/parse.js:127:12)
         at BlockStream.<anonymous> (/home/gu1/xx/node_modules/jspm/node_modules/jspm-github/node_modules/tar/lib/parse.js:47:8)
         at BlockStream.emit (events.js:107:17)
         at BlockStream._emitChunk (/home/gu1/xx/node_modules/jspm/node_modules/jspm-github/node_modules/tar/node_modules/block-stream/block-stream.js:145:10)
         at BlockStream.write (/home/gu1/xx/node_modules/jspm/node_modules/jspm-github/node_modules/tar/node_modules/block-stream/block-stream.js:45:10)
         at Extract.Parse.write (/home/gu1/xx/node_modules/jspm/node_modules/jspm-github/node_modules/tar/lib/parse.js:81:23)
         at IncomingMessage.ondata (_stream_readable.js:540:20)
         at IncomingMessage.emit (events.js:129:20)
         at readableAddChunk (_stream_readable.js:163:16)

warn Error on download for github:bernii/gauge.js, retrying (2).
     Error: invalid tar file
         at Extract.Parse._startEntry (/home/gu1/xx/node_modules/jspm/node_modules/jspm-github/node_modules/tar/lib/parse.js:145:13)
         at Extract.Parse._process (/home/gu1/xx/node_modules/jspm/node_modules/jspm-github/node_modules/tar/lib/parse.js:127:12)
         at BlockStream.<anonymous> (/home/gu1/xx/node_modules/jspm/node_modules/jspm-github/node_modules/tar/lib/parse.js:47:8)
         at BlockStream.emit (events.js:107:17)
         at BlockStream._emitChunk (/home/gu1/xx/node_modules/jspm/node_modules/jspm-github/node_modules/tar/node_modules/block-stream/block-stream.js:145:10)
         at BlockStream.write (/home/gu1/xx/node_modules/jspm/node_modules/jspm-github/node_modules/tar/node_modules/block-stream/block-stream.js:45:10)
         at Extract.Parse.write (/home/gu1/xx/node_modules/jspm/node_modules/jspm-github/node_modules/tar/lib/parse.js:81:23)
         at IncomingMessage.ondata (_stream_readable.js:540:20)
         at IncomingMessage.emit (events.js:129:20)
         at readableAddChunk (_stream_readable.js:163:16)

warn Error on download for github:bernii/gauge.js, retrying (3).
     Error: invalid tar file
         at Extract.Parse._startEntry (/home/gu1/xx/node_modules/jspm/node_modules/jspm-github/node_modules/tar/lib/parse.js:145:13)
         at Extract.Parse._process (/home/gu1/xx/node_modules/jspm/node_modules/jspm-github/node_modules/tar/lib/parse.js:127:12)
         at BlockStream.<anonymous> (/home/gu1/xx/node_modules/jspm/node_modules/jspm-github/node_modules/tar/lib/parse.js:47:8)
         at BlockStream.emit (events.js:107:17)
         at BlockStream._emitChunk (/home/gu1/xx/node_modules/jspm/node_modules/jspm-github/node_modules/tar/node_modules/block-stream/block-stream.js:145:10)
         at BlockStream.write (/home/gu1/xx/node_modules/jspm/node_modules/jspm-github/node_modules/tar/node_modules/block-stream/block-stream.js:45:10)
         at Extract.Parse.write (/home/gu1/xx/node_modules/jspm/node_modules/jspm-github/node_modules/tar/lib/parse.js:81:23)
         at IncomingMessage.ondata (_stream_readable.js:540:20)
         at IncomingMessage.emit (events.js:129:20)
         at readableAddChunk (_stream_readable.js:163:16)

warn Error on download for github:bernii/gauge.js
     Error: invalid tar file
         at Extract.Parse._startEntry (/home/gu1/xx/node_modules/jspm/node_modules/jspm-github/node_modules/tar/lib/parse.js:145:13)
         at Extract.Parse._process (/home/gu1/xx/node_modules/jspm/node_modules/jspm-github/node_modules/tar/lib/parse.js:127:12)
         at BlockStream.<anonymous> (/home/gu1/xx/node_modules/jspm/node_modules/jspm-github/node_modules/tar/lib/parse.js:47:8)
         at BlockStream.emit (events.js:107:17)
         at BlockStream._emitChunk (/home/gu1/xx/node_modules/jspm/node_modules/jspm-github/node_modules/tar/node_modules/block-stream/block-stream.js:145:10)
         at BlockStream.write (/home/gu1/xx/node_modules/jspm/node_modules/jspm-github/node_modules/tar/node_modules/block-stream/block-stream.js:45:10)
         at Extract.Parse.write (/home/gu1/xx/node_modules/jspm/node_modules/jspm-github/node_modules/tar/lib/parse.js:81:23)
         at IncomingMessage.ondata (_stream_readable.js:540:20)
         at IncomingMessage.emit (events.js:129:20)
         at readableAddChunk (_stream_readable.js:163:16)

err  Error downloading github:bernii/gauge.js.

warn Installation changes not saved.
```

**Comment by guybedford** [comment]
@Gu1 thanks for reporting. I've fixed this in https://github.com/jspm/github/commit/c34129152f3ce772fe7bdec309e83d0349f9ea6d.
