### ISSUE TITLE
Getting error token.match not a function on jspm install with latest release jspm-github

### ISSUE THREAD

**Issue by marthinus-engelbrecht** [jspm/github#92]
Hi Guy,

The issues is as described above. When reverting to the previous version the error goes away. Will publish the error log just now.

**Comment by guybedford** [comment]
Please do share the stack if you can.

**Comment by jasonhick** [comment]
I'm also getting this error as are opther developer in my team:
Here's the error:

err  TypeError: token.match is not a function
         at isGithubToken (/Users/Ralphie/Sites/bp-api-ui/node_modules/jspm-github/github.js:82:16)
         at Object.GithubLocation (/Users/Ralphie/Sites/bp-api-ui/node_modules/jspm-github/github.js:105:9)
         at Object.exports.load (/Users/Ralphie/Sites/bp-api-ui/node_modules/jspm/lib/registry.js:73:56)
         at new RegistryPath (/Users/Ralphie/Sites/bp-api-ui/node_modules/jspm/lib/config/loader.js:264:33)
         at Config.read (/Users/Ralphie/Sites/bp-api-ui/node_modules/jspm/lib/config/loader.js:127:26)
         at /Users/Ralphie/Sites/bp-api-ui/node_modules/jspm/lib/config.js:100:26
         at process._tickCallback (node.js:369:9)
         at Function.Module.runMain (module.js:443:11)
         at startup (node.js:139:18)
         at node.js:968:3

err  Unable to load registry github

**Comment by jasonhick** [comment]
Quick update: setting up a token and adding it into the github config fixes this issue.

**Comment by marthinus-engelbrecht** [comment]
We set one up and still got it.

**Comment by marthinus-engelbrecht** [comment]
The stack was exactly the same though. Let me try and reproduce it quickly now. Got sidetracked the other day.

**Comment by marthinus-engelbrecht** [comment]
Ok, I can't seem to reproduce this. Maybe there was a delay in the user being available and by coincidence it became available at the same time as the downgrade. Will open the issue again if I get it again.

**Comment by guybedford** [comment]
I think it applies specifically for the upgrade path. Thanks so much @jasonhick for the stack trace here. I've released a new jspm-github patch which should resolve this now. Please just let me know if you notice anything else.

**Comment by jasonhick** [comment]
Thanks Guy, we'll check this out and come back to you if there are any more issues ;)
